wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1694591306.974737
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.7.13
      5: 0.13.10
      8:
      - 5
batch_size:
  desc: null
  value: 256
discount:
  desc: null
  value: 0.99
env:
  desc: null
  value: outdoor off RL
eval_episodes:
  desc: null
  value: 10
eval_freq:
  desc: null
  value: 10000.0
expectile:
  desc: null
  value: 0.7
max_timesteps:
  desc: null
  value: 1000000.0
model_dir:
  desc: null
  value: /home/kasun/offlineRL/IQL/iql-pytorch/model
normalize:
  desc: null
  value: false
policy:
  desc: null
  value: IQL
save_model:
  desc: null
  value: false
save_video:
  desc: null
  value: false
seed:
  desc: null
  value: 0
tau:
  desc: null
  value: 0.005
temperature:
  desc: null
  value: 3.0
work_dir:
  desc: null
  value: /home/kasun/offlineRL/IQL/iql-pytorch
